### ISSUE TITLE
Utilisation d'une licence homologuée comme la Licence Ouverte 2.0

### ISSUE THREAD

**Issue by bzg** [JimnyGitHub/350-Chaines-Youtube#1]
Bonjour,

l'actuelle licence CC-by-nc 4.0 n'est pas conforme à la loi pour une République numérique qui préconise d'autres licences pour la publication de ce genre d'informations.  Voir https://www.data.gouv.fr/fr/licences pour la liste des licences homologuées.

Pour les contenus qui ne sont pas du code source, la Licence Ouverte 2.0 d'Etalab me semble appropriée.

Je peux faire une PR dans ce sens.

Merci d'avance pour votre retour !

**Comment by JimnyGitHub** [comment]
Bonjour,
La licence notée ici est la même que celle utilisée par la liste.
C'est sur la première page ici : [http://www.culture.gouv.fr/Thematiques/Langue-francaise-et-langues-de-France/Ressources/Ressources-pedagogiques-et-sensibilisation/350-ressources-culturelles-et-scientifiques-francophones-en-video](http://www.culture.gouv.fr/Thematiques/Langue-francaise-et-langues-de-France/Ressources/Ressources-pedagogiques-et-sensibilisation/350-ressources-culturelles-et-scientifiques-francophones-en-video)

**Comment by bzg** [comment]
Bonjour,

merci pour votre réponse. La licence utilisée par la liste est donc erronée aussi.
Savez-vous qui a fait le choix de la licence et qui puis-je contacter pour discuter de cela ?
Pour ne pas vous faire perdre votre temps si vous n'êtes pas la bonne personne.

Merci !

**Comment by JimnyGitHub** [comment]
L’inventaire des chaînes Youtube culturelles et
scientifiques francophones a été réalisé par
Mathilde Hutin, avec le soutien de la Délégation
générale à la langue française et aux langues de
France, ministère de la Culture

Mathilde Hutin : https://twitter.com/mathhtn

Délégation générale à la langue française et aux langues de France
6, rue des Pyramides 75001 PARIS

Téléphone : 33 (0)1 40 15 80 00
   
Courriel :
dglf[alt]culture.gouv.fr

**Comment by bzg** [comment]
Merci !

**Comment by bzg** [comment]
J'ai tenté d'envoyer un mail, mais je n'ai pas reçu de réponse. Si vous avez des moyens de faire remonter l'information, je suis preneur. Merci !

**Comment by JimnyGitHub** [comment]
Pas plus de moyen pour faire remonter l'info que l'idée du mail
je peux le tenter aussi, peut etre que s'il y en a plusieurs cela peut aider

**Comment by bzg** [comment]
Oui, cela pourrait aider. Merci d'avance !

**Comment by bzg** [comment]
Bonjour, avez-vous eu plus de succès que moi ? Merci !

**Comment by JimnyGitHub** [comment]
Non, aucun succès :-1:

**Comment by bzg** [comment]
C'est bien dommage.  Merci d'avoir essayé.
